basePath: /
consumes:
    - application/json
definitions:
    ErrorResponse:
        properties:
            code:
                type: string
            error:
                type: string
        required:
            - error
            - code
        type: object
    Field:
        properties:
            required:
                type: boolean
            type:
                enum:
                    - string
                    - bool
                type: string
            unique:
                type: boolean
        required:
            - type
            - required
            - unique
        type: object
    FieldConfig:
        properties:
            participation:
                additionalProperties:
                    $ref: '#/definitions/Field'
                type: object
            user:
                additionalProperties:
                    $ref: '#/definitions/Field'
                type: object
        required:
            - user
            - participation
        type: object
    Game:
        properties:
            id:
                type: string
            name:
                type: string
        required:
            - id
            - name
        type: object
    GetGameResponse:
        $ref: '#/definitions/Game'
    GetGamesResponse:
        items:
            $ref: '#/definitions/Game'
        type: array
    GetParticipationMethodsResponse:
        items:
            $ref: '#/definitions/ParticipationMethod'
        type: array
    GetPrizesResponse:
        items:
            $ref: '#/definitions/Prize'
        type: array
    GetUserResponse:
        $ref: '#/definitions/User'
    GetUsersResponse:
        items:
            $ref: '#/definitions/User'
        type: array
    GetWonPrizesResponse:
        items:
            $ref: '#/definitions/WonPrize'
        type: array
    Participation:
        properties:
            created_at: {}
            fields:
                additionalProperties: {}
                type: object
            participation_id:
                type: string
            participation_method_id:
                type: string
            user_id:
                type: string
        required:
            - participation_id
            - participation_method_id
            - user_id
            - created_at
            - fields
        type: object
    ParticipationMethod:
        properties:
            fields:
                $ref: '#/definitions/FieldConfig'
            game_id:
                type: string
            id:
                type: string
            limit:
                enum:
                    - none
                    - daily
                type: string
            name:
                type: string
        required:
            - id
            - game_id
            - name
            - limit
            - fields
        type: object
    ParticipationRequest:
        properties:
            fields:
                additionalProperties: {}
                type: object
        required:
            - fields
        type: object
    ParticipationResponse:
        properties:
            prizes:
                items:
                    $ref: '#/definitions/PublicPrize'
                type: array
        required:
            - prizes
        type: object
    Prize:
        properties:
            count:
                format: int64
                type: integer
            description:
                type: string
            gameId:
                type: string
            id:
                type: string
            image_url:
                type: string
            name:
                type: string
        required:
            - id
            - gameId
            - name
            - description
            - count
        type: object
    PublicPrize:
        properties:
            description:
                type: string
            image_url:
                type: string
            name:
                type: string
        required:
            - name
            - description
        type: object
    User:
        properties:
            additional_fields:
                additionalProperties: {}
                type: object
            address:
                type: string
            email:
                type: string
            game_id:
                type: string
            id:
                type: string
            phone:
                type: string
        required:
            - id
            - game_id
            - additional_fields
        type: object
    WonPrize:
        properties:
            participation:
                $ref: '#/definitions/Participation'
            prize:
                $ref: '#/definitions/Prize'
            user:
                $ref: '#/definitions/User'
        required:
            - prize
            - participation
            - user
        type: object
host: localhost:8080
info:
    description: Backend for prize games
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    title: Prizer Public API
    version: "1.0"
paths:
    /participationMethod/{participationMethodId}/participate:
        post:
            operationId: participate
            parameters:
                - in: path
                  name: participationMethodId
                  required: true
                  type: string
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/ParticipationRequest'
                    type: object
            responses:
                "200":
                    description: ParticipationResponse
                    schema:
                        $ref: '#/definitions/ParticipationResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "403":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - participationMethod
produces:
    - application/json
schemes:
    - http
    - https
swagger: "2.0"
