basePath: /
consumes:
    - application/json
definitions:
    ErrorResponse:
        properties:
            code:
                type: string
            error:
                type: string
        type: object
    Game:
        properties:
            id:
                type: string
            name:
                type: string
        type: object
    GetGameResponse:
        $ref: '#/definitions/Game'
    GetPrizesResponse:
        items:
            $ref: '#/definitions/Prize'
        type: array
    GetUsersResponse:
        items:
            $ref: '#/definitions/User'
        type: array
    ParticipationRequest:
        properties:
            fields:
                additionalProperties: {}
                type: object
        type: object
    ParticipationResponse:
        properties:
            prizes:
                items:
                    $ref: '#/definitions/PublicPrize'
                type: array
        type: object
    Prize:
        properties:
            count:
                format: int64
                type: integer
            description:
                type: string
            gameId:
                type: string
            id:
                type: string
            name:
                type: string
        type: object
    PublicPrize:
        properties:
            description:
                type: string
            name:
                type: string
        type: object
    User:
        properties:
            additional_fields:
                additionalProperties: {}
                type: object
            address:
                type: string
            email:
                type: string
            game_id:
                type: string
            id:
                type: string
            phone:
                type: string
        type: object
host: localhost:8080
info:
    description: Backend for prize games
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    title: Prizer Public API
    version: "1.0"
paths:
    /participationMethod/{participationMethodId}/participate:
        post:
            operationId: participate
            parameters:
                - in: path
                  name: participationMethodId
                  type: string
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/ParticipationRequest'
                    type: object
            responses:
                "200":
                    description: ParticipationResponse
                    schema:
                        $ref: '#/definitions/ParticipationResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "403":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - participationMethod
produces:
    - application/json
schemes:
    - http
    - https
swagger: "2.0"
